import json, random
from os import stat
import matplotlib.pyplot as plt
data = '''{
   "_links":{
      "self":{
         "href":"https://python-bot-mekmw5idnq-em.a.run.app"
      }
   },
   "arena":{
      "dims":[
         24,
         18
      ],
      "state":{
         "https://python-bot-aa24kfcuaq-de.a.run.app":{
            "x":7,
            "y":14,
            "direction":"N",
            "wasHit":false,
            "score":11
         },
         "https://python-bot-wzf2k7csnq-wl.a.run.app":{
            "x":7,
            "y":13,
            "direction":"N",
            "wasHit":false,
            "score":1
         },
         "https://python-bot-452ho4dira-as.a.run.app":{
            "x":13,
            "y":14,
            "direction":"E",
            "wasHit":false,
            "score":1
         },
         "https://nodejs-bot-abpyq2ydaa-as.a.run.app":{
            "x":14,
            "y":16,
            "direction":"S",
            "wasHit":false,
            "score":-9
         },
         "https://water-splash-bot-x-7u7o4efuca-uc.a.run.app":{
            "x":15,
            "y":1,
            "direction":"E",
            "wasHit":false,
            "score":73
         },
         "https://python-bot-xpu2myq57q-uc.a.run.app":{
            "x":0,
            "y":10,
            "direction":"S",
            "wasHit":false,
            "score":5
         },
         "https://java-springboot-bot-zkqghyzc6a-em.a.run.app":{
            "x":23,
            "y":10,
            "direction":"E",
            "wasHit":false,
            "score":54
         },
         "https://java-springboot-bot-3geshnyd6a-em.a.run.app":{
            "x":10,
            "y":5,
            "direction":"E",
            "wasHit":false,
            "score":-36
         },
         "https://java-springboot-bot-onap3e75za-uc.a.run.app":{
            "x":3,
            "y":13,
            "direction":"W",
            "wasHit":false,
            "score":-7
         },
         "https://java-springboot-bot-yz4c5w7fya-as.a.run.app":{
            "x":9,
            "y":14,
            "direction":"S",
            "wasHit":false,
            "score":5
         },
         "https://python-bot-f3zqokzsua-uc.a.run.app":{
            "x":21,
            "y":11,
            "direction":"W",
            "wasHit":false,
            "score":1
         },
         "https://java-springboot-bot-3r56t5mvoa-uc.a.run.app":{
            "x":18,
            "y":6,
            "direction":"W",
            "wasHit":false,
            "score":3
         },
         "https://python-bot-ksvj7q4wga-em.a.run.app":{
            "x":20,
            "y":3,
            "direction":"W",
            "wasHit":false,
            "score":-4
         },
         "https://python-bot-57yudx7dzq-uc.a.run.app":{
            "x":6,
            "y":7,
            "direction":"W",
            "wasHit":false,
            "score":-1
         },
         "https://python-bot-dnuf5dybaq-em.a.run.app/":{
            "x":4,
            "y":15,
            "direction":"S",
            "wasHit":false,
            "score":0
         },
         "https://nodejs-bot-mdwpwk4fwa-as.a.run.app":{
            "x":23,
            "y":11,
            "direction":"E",
            "wasHit":false,
            "score":-47
         },
         "https://java-springboot-bot-pcykazqnla-an.a.run.app":{
            "x":0,
            "y":9,
            "direction":"W",
            "wasHit":false,
            "score":-1
         },
         "https://python-bot-36ufadraiq-et.a.run.app":{
            "x":15,
            "y":2,
            "direction":"N",
            "wasHit":false,
            "score":3
         },
         "https://python-bot-adlhc57fcq-de.a.run.app":{
            "x":21,
            "y":14,
            "direction":"E",
            "wasHit":false,
            "score":-14
         },
         "https://silkroad-37aoukcprq-uc.a.run.app":{
            "x":19,
            "y":13,
            "direction":"W",
            "wasHit":false,
            "score":-13
         },
         "https://java-springboot-bot-t34nqg3eqq-as.a.run.app":{
            "x":5,
            "y":11,
            "direction":"N",
            "wasHit":false,
            "score":-37
         },
         "https://python-bot-a6xe4m4rma-uc.a.run.app":{
            "x":6,
            "y":12,
            "direction":"S",
            "wasHit":true,
            "score":68
         },
         "https://nodejskrishna-bot-o4bh7zlqoa-uc.a.run.app":{
            "x":10,
            "y":17,
            "direction":"E",
            "wasHit":false,
            "score":-25
         },
         "https://java-springboot-bot-vt7gk6uhyq-em.a.run.app":{
            "x":21,
            "y":13,
            "direction":"N",
            "wasHit":false,
            "score":6
         },
         "https://nodejs-bot-zx4wpxe3oq-em.a.run.app":{
            "x":21,
            "y":4,
            "direction":"E",
            "wasHit":false,
            "score":4
         },
         "https://python-bot-qi5lo24wiq-uc.a.run.app":{
            "x":21,
            "y":15,
            "direction":"E",
            "wasHit":false,
            "score":8
         },
         "https://python-bot-ef3gem4d6a-uc.a.run.app":{
            "x":4,
            "y":10,
            "direction":"W",
            "wasHit":true,
            "score":-8
         },
         "https://silkroad-q-ia62jjez4a-uc.a.run.app":{
            "x":12,
            "y":17,
            "direction":"W",
            "wasHit":true,
            "score":15
         },
         "https://python-bot-jevqo63kwq-em.a.run.app":{
            "x":1,
            "y":8,
            "direction":"S",
            "wasHit":false,
            "score":3
         },
         "https://python-bot-h4h5dzojvq-em.a.run.app/":{
            "x":2,
            "y":15,
            "direction":"N",
            "wasHit":false,
            "score":0
         },
         "https://python-bot-qhknff7wta-em.a.run.app":{
            "x":22,
            "y":9,
            "direction":"N",
            "wasHit":false,
            "score":-11
         },
         "https://krsjava-springboot-bot-7juvvzwy4q-uc.a.run.app":{
            "x":12,
            "y":3,
            "direction":"N",
            "wasHit":false,
            "score":-9
         },
         "https://python-bot-4bb2kw2uaq-uc.a.run.app":{
            "x":16,
            "y":1,
            "direction":"S",
            "wasHit":true,
            "score":-71
         },
         "https://java-springboot-bot-lhk63fny4q-uc.a.run.app":{
            "x":23,
            "y":0,
            "direction":"W",
            "wasHit":false,
            "score":-27
         },
         "https://94e9-172-105-34-203.ngrok.io":{
            "x":10,
            "y":12,
            "direction":"E",
            "wasHit":false,
            "score":-13
         },
         "https://java-springboot-bot-chd6tovdjq-an.a.run.app":{
            "x":8,
            "y":13,
            "direction":"S",
            "wasHit":false,
            "score":-6
         },
         "https://java-springboot-bot-tlz3sxce6q-as.a.run.app":{
            "x":8,
            "y":9,
            "direction":"E",
            "wasHit":false,
            "score":4
         },
         "https://jay-bot-4rmtwapiia-uc.a.run.app":{
            "x":8,
            "y":4,
            "direction":"E",
            "wasHit":false,
            "score":58
         },
         "https://java-springboot-bot-zkppv55o6q-as.a.run.app":{
            "x":5,
            "y":14,
            "direction":"N",
            "wasHit":false,
            "score":-89
         },
         "https://nodejs-bot-6laaclswga-em.a.run.app":{
            "x":14,
            "y":4,
            "direction":"S",
            "wasHit":true,
            "score":-6
         },
         "https://python-bot-rkd6qhgnpa-uc.a.run.app":{
            "x":14,
            "y":17,
            "direction":"W",
            "wasHit":false,
            "score":87
         },
         "https://java-springboot-bot-oiteqcivwa-uc.a.run.app":{
            "x":2,
            "y":11,
            "direction":"W",
            "wasHit":false,
            "score":-18
         },
         "https://python-bot-or3i5dcs6q-as.a.run.app":{
            "x":11,
            "y":7,
            "direction":"E",
            "wasHit":false,
            "score":7
         },
         "https://java-springboot-bot-eefhkimobq-uc.a.run.app":{
            "x":16,
            "y":8,
            "direction":"W",
            "wasHit":false,
            "score":0
         },
         "https://java-springboot-bot-oaiu5q5ata-de.a.run.app":{
            "x":23,
            "y":17,
            "direction":"W",
            "wasHit":true,
            "score":1
         },
         "https://nodejs-bot-rxftb3sw2a-uc.a.run.app":{
            "x":6,
            "y":15,
            "direction":"N",
            "wasHit":false,
            "score":64
         },
         "https://python-bot-mekmw5idnq-em.a.run.app":{
            "x":2,
            "y":9,
            "direction":"E",
            "wasHit":false,
            "score":22
         },
         "https://python-bot-qgubgqv6bq-uc.a.run.app":{
            "x":12,
            "y":7,
            "direction":"S",
            "wasHit":false,
            "score":-6
         },
         "https://python-bot-hjasgo3yvq-uc.a.run.app":{
            "x":20,
            "y":12,
            "direction":"E",
            "wasHit":false,
            "score":-1
         },
         "https://nodejs-bot-n33wt2kama-as.a.run.app":{
            "x":11,
            "y":4,
            "direction":"S",
            "wasHit":true,
            "score":1
         },
         "https://java-springboot-bot-dd6ysknx4q-as.a.run.app/":{
            "x":3,
            "y":7,
            "direction":"W",
            "wasHit":false,
            "score":-9
         },
         "https://python-bot-bl3rxjcqjq-as.a.run.app":{
            "x":8,
            "y":10,
            "direction":"E",
            "wasHit":false,
            "score":-6
         },
         "https://java-springboot-bot-r5lsmc2n3q-an.a.run.app":{
            "x":20,
            "y":17,
            "direction":"S",
            "wasHit":true,
            "score":8
         },
         "https://java-springboot-bot-gwlv4a5zxa-as.a.run.app":{
            "x":11,
            "y":6,
            "direction":"W",
            "wasHit":false,
            "score":-6
         },
         "https://java-springboot-bot-facwzt3hca-et.a.run.app":{
            "x":20,
            "y":15,
            "direction":"N",
            "wasHit":false,
            "score":2
         },
         "https://python-bot-j4bgsvwz3a-uc.a.run.app":{
            "x":14,
            "y":1,
            "direction":"S",
            "wasHit":false,
            "score":7
         },
         "https://python-bot-oskyweulvq-as.a.run.app/":{
            "x":19,
            "y":9,
            "direction":"E",
            "wasHit":false,
            "score":-26
         },
         "https://python-bot-iiqpxb2opq-uc.a.run.app":{
            "x":3,
            "y":6,
            "direction":"S",
            "wasHit":false,
            "score":4
         },
         "https://python-bot-emv67touba-as.a.run.app":{
            "x":8,
            "y":0,
            "direction":"N",
            "wasHit":false,
            "score":-11
         },
         "https://nodejs-bot-44oaeskbqa-as.a.run.app":{
            "x":11,
            "y":17,
            "direction":"S",
            "wasHit":false,
            "score":-66
         },
         "https://java-springboot-bot-24rw4b57fq-de.a.run.app":{
            "x":23,
            "y":14,
            "direction":"S",
            "wasHit":false,
            "score":63
         },
         "https://python-bot-fkv622tflq-em.a.run.app":{
            "x":10,
            "y":11,
            "direction":"S",
            "wasHit":true,
            "score":-97
         },
         "https://python-bot-36ufadraiq-as.a.run.app":{
            "x":17,
            "y":8,
            "direction":"W",
            "wasHit":false,
            "score":1
         },
         "https://python-bot-gfrigbbcia-uc.a.run.app":{
            "x":5,
            "y":7,
            "direction":"S",
            "wasHit":false,
            "score":-3
         },
         "https://nodejs-bot-gqugfjrxja-uc.a.run.app":{
            "x":10,
            "y":9,
            "direction":"S",
            "wasHit":false,
            "score":93
         }
      }
   }
}'''

state = []
mystate = []
mydata = json.loads(data)
def formatData():
    global state, mystate
    myURL = mydata['_links']['self']['href']
    for key in mydata['arena']['state'].keys():
        if key==myURL:
            mystate = [mydata['arena']['state'][key]['x'],mydata['arena']['state'][key]['y'],mydata['arena']['state'][key]['direction'],mydata['arena']['state'][key]['wasHit'],mydata['arena']['state'][key]['score']]
        else:
            state.append([mydata['arena']['state'][key]['x'],mydata['arena']['state'][key]['y'],mydata['arena']['state'][key]['direction'],mydata['arena']['state'][key]['wasHit'],mydata['arena']['state'][key]['score']])

formatData()
print("My coordinates are :" + str(mystate))
# for player in state:
    # player - 
'''
X = [x-X[myPosition] for x in X]
Y = [y-Y[myPosition] for y in Y]
state = list(zip(X,Y,D,wasHit,score))
'''
print(state)
plt.gca().invert_yaxis()
plt.scatter([x[0] for x in state],[x[1] for x in state])
plt.scatter(mystate[0],mystate[1],marker="s")
plt.show()
